
export enum FilmStyle {
    BLACK_AND_WHITE = 'BLACK_AND_WHITE',
    KODAK_GOLD = 'KODAK_GOLD',
    HP5 = 'HP5',
    KODAK_PORTRA = 'KODAK_PORTRA',
    CINESTILL_800T = 'CINESTILL_800T',
    FUJI_SUPERIA = 'FUJI_SUPERIA',
}
